version: '3'

networks:
  LEMP:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx1
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ./code:/code
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - LEMP

  pgsql:
    image: postgres:11-alpine
    container_name: pgsql1
    ports:
      - "${POSTGRES_PORT}:5432"
    depends_on:
      - nginx
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    networks:
      - LEMP

  redis:
    image: bitnami/redis:latest
    container_name: redis1
    ports:
      - "${REDIS_PORT}:6379"
    depends_on:
      - nginx
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ${REDIS_DATA}:/bitnami/redis/data
    networks:
      - LEMP
  

  # rabbitmq:
  #   image: rabbitmq:3-alpine
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   depends_on:
  #     - nginx
  #   environment:
  #     - RABBITMQ_DEFAULT_USER="admin"
  #     - RABBITMQ_DEFAULT_PASS="112233"
  #   volumes:
  #     - ./rabbitmq/etc/:/etc/rabbitmq
  #     - ./rabbitmq/data/:/var/lib/rabbitmq
  #     - ./rabbitmq/logs/:/var/log/rabbitmq
  #   networks:
  #     - LEMP
  php:
    build:
      context: ./php
    container_name: php74
    volumes:
      - ./code:/code
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1 idekey=PHPSTORM remote_port=9001 remote_connect_back=1"
      PHP_IDE_CONFIG: "serverName=php"

    ports:
      - "9000:9000"
    networks:
      - LEMP

  mysql:
       image: mysql
       command: --default-authentication-plugin=mysql_native_password
       restart: always
       ports:
         - "3306"
       environment:
         MYSQL_ROOT_PASSWORD: 112233
       depends_on:
         - nginx
       volumes:
           - ./mysql:/var/lib/mysql
       networks:
         - LEMP

